### ISSUE TITLE
Test not passing

### ISSUE THREAD

**Issue by michael4reynolds** [localvoid/uix_example_tests#1]
Running the tests returns the following:

ERROR
Basic Component Hello World. Test failed: Caught The null object does not have a getter 'clock'. NoSuchMethodError: method not found: 'clock' Receiver: null Arguments: []
dart:core                                            Object.noSuchMethod
package:uix/src/component.dart 66:23                 Component.update
package:uix/src/utils.dart 22:19                     injectComponent
test_basic.dart 13:22                                main.<fn>.<fn>
package:unittest/src/internal_test_case.dart 120:37  run.<fn>

**Comment by localvoid** [comment]
Thanks, it is now required to initialize Uix library before running tests.

Just add `initUix()`. It creates Scheduler() instance.

All Components now implement `RevisionedNode` interface https://github.com/localvoid/uix/blob/master/lib/src/data/node.dart#L10-L17 ,revision is updated when `updateState()` returns `true`.

It can be used to implement fast dirty-checking for mutable data.
